# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link1
  pid: {p: 700.0, i: 50, d: 70.0}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link1_link2
  pid: {p: 700.0, i: 50, d: 70.0}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link2_link3
  pid: {p: 700.0, i: 50, d: 70.0}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link3_link4
  pid: {p: 700.0, i: 50, d: 70.0}

joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link4_gripper_base
  pid: {p: 700.0, i: 50, d: 70.0}

gripperL_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_base_claw_L
  pid: {p: 700.0, i: 50, d: 70.0}

gripperR_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_base_claw_R
  pid: {p: 700.0, i: 50, d: 70.0}


